name = "yostos-persona"
main = "src/worker/index.ts"
compatibility_date = "2025-03-19"

routes = [
  { pattern = "ask.codedchords.dev", custom_domain = true }
]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "yostos-persona"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "a37f9b9c0d2e4f72a4d23219dfe50488"

[assets]
directory = "src/frontend"
binding = "ASSETS"
